### ISSUE TITLE
I cannot make things look like in markbot

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/components-on-a-grid#1]
Hi, so I have several problem: 
1. I cannot make the 1rem gutter without putting margin in the body tag, but apparently markbot doesn't want it
2. Since I switch to grid-template-areas I cannot make two photos become the same size at each other. 

Here is the screenshot

@HannahDelaney
@hellachella

![Screen Shot 2020-09-17 at 3 32 51 PM](https://user-images.githubusercontent.com/55094125/93446700-b5df2000-f8fb-11ea-83d3-1f52ea2de3f9.png)

**Comment by Sam-Le68** [comment]
@JessJodoin pls help me

**Comment by JessJodoin** [comment]
Hey is it cool if I start a slack DM to go through it? 😄
